spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trufas
    username: isamaluza
    password: 351917
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql
 
server:
  port: 8081